name: dsc180a-q1-final
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.4=pyhd8ed1ab_1
  - asttokens=3.0.1=pyhd8ed1ab_0
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.12.2=hca03da5_0
  - comm=0.2.3=pyhe01879c_0
  - debugpy=1.8.16=py311h50f4ffc_1
  - decorator=5.2.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.3=h982b769_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipython=9.8.0=pyh53cf698_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - krb5=1.21.3=h237132a_0
  - libcxx=20.1.8=hd7fd590_1
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libffi=3.4.4=hca03da5_1
  - libsodium=1.0.20=h99b78c6_0
  - libzlib=1.3.1=h5f15de7_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - ncurses=6.5=hee39554_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.6.0=h5503f6c_0
  - packaging=25.0=pyh29332c3_1
  - parso=0.8.5=pyhcf101f3_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pip=25.3=pyhc872135_0
  - platformdirs=4.5.1=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.0.0=py311haa24f5a_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.11.14=hf701271_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - pyzmq=27.1.0=py311h5a8c52c_1
  - readline=8.3=h0b18652_0
  - setuptools=80.9.0=py311hca03da5_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.51.0=hab6afd1_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.15=hcd8a7d5_0
  - tornado=6.5.1=py311h80987f9_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=py311hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zeromq=4.3.5=h888dc83_9
  - zipp=3.23.0=pyhcf101f3_1
  - zlib=1.3.1=h5f15de7_0
  - pip:
      - beautifulsoup4==4.12.2
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - contourpy==1.3.3
      - cycler==0.12.1
      - fonttools==4.61.0
      - idna==3.11
      - ipykernel==6.25.2
      - joblib==1.5.2
      - kiwisolver==1.4.9
      - matplotlib==3.8.1
      - narwhals==2.13.0
      - numpy==1.25.2
      - pandas==2.1.1
      - pillow==12.0.0
      - plotly==6.1.2
      - pot==0.9.6
      - pyparsing==3.2.5
      - pytz==2025.2
      - requests==2.30.0
      - scikit-learn==1.3.1
      - scipy==1.11.3
      - soupsieve==2.8
      - threadpoolctl==3.6.0
      - tzdata==2025.2
      - urllib3==2.5.0
prefix: /opt/anaconda3/envs/dsc180a-q1-final
